###############
## 
####

GPU: [0,1]

VERBOSE: True

MODEL:
  MODE: 'Deraining'
  SESSION: 'MPRNet'

# Optimization arguments.
OPTIM:
  BATCH_SIZE: 64
  NUM_EPOCHS: 26
  LR_INITIAL: 1e-4
  LR_MIN: 1e-6
  # BETA1: 0.9

TRAINING:
  VAL_AFTER_EVERY: 1
  RESUME: True
  TRAIN_PS: 128
  VAL_PS: 112
  TRAIN_DIR: './dataset/pristine_images_color_noisy_25'       # path to training data
  VAL_DIR: './dataset/pristine_images_color_noisy_25' # path to validation data
  SAVE_DIR: './checkpoint_denoising25/'           # path to save models and images
  # SAVE_IMAGES: False



